Completed prep-css-flexbox exercise-David Gonzalez
David-Gonzalez11/prep-0122-code-solutions pull request #8
Opened 2022-01-14 05:47 UTC by David-Gonzalez11

![#1 prep-css-flexbox](https://user-images.githubusercontent.com/24907191/149458163-c4907b62-dccb-4f31-9c24-4816866f73db.png)
![#2 prep-css-flexbox](https://user-images.githubusercontent.com/24907191/149458177-b7fa5852-c967-4e17-a860-a65df00c7dbd.png)
![#3prep-css-flexbox](https://user-images.githubusercontent.com/24907191/149458188-184cac7d-9e5e-4fcd-affd-da65012cd338.png)
![#4 prep-css flex-box](https://user-images.githubusercontent.com/24907191/149458202-00656b1a-8543-4efc-9271-cf03e72ca429.png)

2022-01-14 20:59 UTC, thebearingedge requested changes

2022-01-14 20:59 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +      flex-basis: 25%;
Here you'll want to put your `flex-basis` on the `.card-wrapper` instead.

2022-01-14 20:59 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      flex-basis: calc(100% / 3);
Here you'll want to put your `flex-basis` on the `.card-wrapper` instead.

2022-01-15 20:18 UTC, David-Gonzalez11 commented on prep-css-flexbox/justify-content.html
> +      flex-basis: 25%;
<img width="1021" alt="new new " src="https://user-images.githubusercontent.com/24907191/149636502-22eaf677-8e6c-45a0-986e-738d615f5280.png">
<img width="1010" alt="NEW NEw" src="https://user-images.githubusercontent.com/24907191/149636505-ca6c8b3e-2156-40a6-a971-84337405b144.png">

2022-01-15 20:55 UTC, thebearingedge approved these changes

2022-01-17 08:30 UTC, merged